In [2]:
import pandas as pd
from matplotlib.widgets import CheckButtons
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.pyplot import figure

import ipywidgets as wg
from IPython.display import display
from ipywidgets import Label, Layout, HBox

In [3]:
# ไฟล์นำมาคำนวนค่าเฉลี่ย,thrsehold
cols_to_use = ['Character', 'test' ,'train']
Tthreshold = pd.read_csv(f'1 key_test_n_train/test_n_train_a13.csv' ,usecols = cols_to_use)
Tthreshold

   Character        test       train
0          A  1052.96290  1005.90630
1          B  1022.68400   756.20170
2          C   529.18256   775.33466
3          D   810.09840   934.15094
4          E  1062.85300  1059.33330
5          F  1050.17490   982.15270
6          G  1168.36850  1026.53660
7          H   957.40076   954.12470
8          I   866.62320   893.47610
9          J   609.06050   718.93585
10         K   939.66034   736.41284
11         L   584.32450   980.56450
12         M   991.62860   966.53110
13         N   834.78920   776.20917
14         O   964.01166  1015.84515
15         P   772.63190   622.51560
16         Q  1079.59420  1347.56430
17         R  1029.03820   834.26263
18         S   969.92210   861.87380
19         T   773.44910   645.34436
20         U   636.26654   743.25000
21         V  1137.68200  1113.27640
22         W   921.44620   899.25775
23         X  1091.91590   562.81160
24         Y  1063.78900   512.96124
25         Z  1256.34550   854.76526

In [4]:
# รับข้อมูลมาเทียบ
testcompare  = pd.read_csv(f"1 key/a13.csv",usecols = ["Character" ,"Time"])

# ตัด + เรียงข้อมูลเทียบ
testcompare  = testcompare[testcompare.Time >= 0]
testcompare  = testcompare[testcompare.Time <= 10000]
testcompare  = testcompare.sort_values(by=['Character'])

# สุ่มตัวอย่างของเทียบ
testcompare = testcompare.groupby("Character").sample(n=1,replace=True)
testcompare

      Character  Time
27584         A  1053
2451          B  1131
502           C  1156
10308         D  1164
18545         E   905
7792          F  1717
8012          G  1081
12996         H  1407
7512          I  1028
6315          J  1022
13646         K  1017
27453         L   959
13315         M   995
27762         N  1011
15442         O   889
25380         P  1158
18320         Q  1113
20155         R   945
8604          S  2392
5613          T   781
4273          U   904
25656         V  1082
4082          W   977
8254          X  1219
14178         Y   989
36959         Z  6248

## Test

In [5]:
# threshold Test
Test = pd.DataFrame()
Test['Character'] = Tthreshold['Character']
Test['TestPredictPlot'] = Tthreshold['test']
Test['Per5'] = Tthreshold['test'] * 0.05
Test['Per10'] = Tthreshold['test'] * 0.1
Test['Per15'] = Tthreshold['test'] * 0.15
Test['Per20'] = Tthreshold['test'] * 0.2

Test['T_Per5'] = Tthreshold['test'] + Test['Per5']
Test['B_Per5'] = Tthreshold['test'] - Test['Per5']

Test['T_Per10'] = Tthreshold['test'] + Test['Per10']
Test['B_Per10'] = Tthreshold['test'] - Test['Per10']

Test['T_Per15'] = Tthreshold['test'] + Test['Per15']
Test['B_Per15'] = Tthreshold['test'] - Test['Per15']

Test['T_Per20'] = Tthreshold['test'] + Test['Per20']
Test['B_Per20'] = Tthreshold['test'] - Test['Per20']

Test

,Character,TestPredictPlot,Per5,Per10,Per15,Per20,T_Per5,B_Per5,T_Per10,B_Per10,T_Per15,B_Per15,T_Per20,B_Per20
0,A,1052.96290,52.648145,105.296290,157.944435,210.592580,1105.611045,1000.314755,1158.259190,947.666610,1210.907335,895.018465,1263.555480,842.370320
1,B,1022.68400,51.134200,102.268400,153.402600,204.536800,1073.818200,971.549800,1124.952400,920.415600,1176.086600,869.281400,1227.220800,818.147200
2,C,529.18256,26.459128,52.918256,79.377384,105.836512,555.641688,502.723432,582.100816,476.264304,608.559944,449.805176,635.019072,423.346048
3,D,810.09840,40.504920,81.009840,121.514760,162.019680,850.603320,769.593480,891.108240,729.088560,931.613160,688.583640,972.118080,648.078720
4,E,1062.85300,53.142650,106.285300,159.427950,212.570600,1115.995650,1009.710350,1169.138300,956.567700,1222.280950,903.425050,1275.423600,850.282400
5,F,1050.17490,52.508745,105.017490,157.526235,210.034980,1102.683645,997.666155,1155.192390,945.157410,1207.701135,892.648665,1260.209880,840.139920
6,G,1168.36850,58.418425,116.836850,175.255275,233.673700,1226.786925,1109.950075,1285.205350,1051.531650,1343.623775,993.113225,1402.042200,934.694800
7,H,957.40076,47.870038,95.740076,143.610114,191.480152,1005.270798,909.530722,1053.140836,861.660684,1101.010874,813.790646,1148.880912,765.920608
8,I,866.62320,43.331160,86.662320,129.993480,173.324640,909.954360,823.292040,953.285520,779.960880,996.616680,736.629720,1039.947840,693.298560
9,J,609.06050,30.453025,60.906050,91.359075,121.812100,639.513525,578.607475,669.966550,548.154450,700.419575,517.701425,730.872600,487.248400
10,K,939.66034,46.983017,93.966034,140.949051,187.932068,986.643357,892.677323,1033.626374,845.694306,1080.609391,798.711289,1127.592408,751.728272
11,L,584.32450,29.216225,58.432450,87.648675,116.864900,613.540725,555.108275,642.756950,525.892050,671.973175,496.675825,701.189400,467.459600
12,M,991.62860,49.581430,99.162860,148.744290,198.325720,1041.210030,942.047170,1090.791460,892.465740,1140.372890,842.884310,1189.954320,793.302880
13,N,834.78920,41.739460,83.478920,125.218380,166.957840,876.528660,793.049740,918.268120,751.310280,960.007580,709.570820,1001.747040,667.831360
14,O,964.01166,48.200583,96.401166,144.601749,192.802332,1012.212243,915.811077,1060.412826,867.610494,1108.613409,819.409911,1156.813992,771.209328
15,P,772.63190,38.631595,77.263190,115.894785,154.526380,811.263495,734.000305,849.895090,695.368710,888.526685,656.737115,927.158280,618.105520
16,Q,1079.59420,53.979710,107.959420,161.939130,215.918840,1133.573910,1025.614490,1187.553620,971.634780,1241.533330,917.655070,1295.513040,863.675360
17,R,1029.03820,51.451910,102.903820,154.355730,205.807640,1080.490110,977.586290,1131.942020,926.134380,1183.393930,874.682470,1234.845840,823.230560
18,S,969.92210,48.496105,96.992210,145.488315,193.984420,1018.418205,921.425995,1066.914310,872.929890,1115.410415,824.433785,1163.906520,775.937680
19,T,773.44910,38.672455,77.344910,116.017365,154.689820,812.121555,734.776645,850.794010,696.104190,889.466465,657.431735,928.138920,618.759280
20,U,636.26654,31.813327,63.626654,95.439981,127.253308,668.079867,604.453213,699.893194,572.639886,731.706521,540.826559,763.519848,509.013232
21,V,1137.68200,56.884100,113.768200,170.652300,227.536400,1194.566100,1080.797900,1251.450200,1023.913800,1308.334300,967.029700,1365.218400,910.145600
22,W,921.44620,46.072310,92.144620,138.216930,184.289240,967.518510,875.373890,1013.590820,829.301580,1059.663130,783.229270,1105.735440,737.156960
23,X,1091.91590,54.595795,109.191590,163.787385,218.383180,1146.511695,1037.320105,1201.107490,982.724310,1255.703285,928.128515,1310.299080,873.532720
24,Y,1063.78900,53.189450,106.378900,159.568350,212.757800,1116.978450,1010.599550,1170.167900,957.410100,1223.357350,904.220650,1276.546800,851.031200
25,Z,1256.34550,62.817275,125.634550,188.451825,251.269100,1319.162775,1193.528225,1381.980050,1130.710950,1444.797325,1067.893675,1507.614600,1005.076400

In [6]:
check_userTest = pd.DataFrame()

# เก็บค่าที่อยู่นอกหรือใน teshold
checker = []
check_userTest['Character'] = testcompare['Character'] 
    
# แปลงเป็น dic
data = dict(zip(testcompare['Character'],testcompare['Time']))

t5 = dict(zip(Test.Character,Test['T_Per5']))
b5 = dict(zip(Test.Character,Test['B_Per5']))

t10 = dict(zip(Test.Character,Test['T_Per10']))
b10 = dict(zip(Test.Character,Test['B_Per10']))

t15 = dict(zip(Test.Character,Test['T_Per15']))
b15 = dict(zip(Test.Character,Test['B_Per15']))

t20 = dict(zip(Test.Character,Test['T_Per20']))
b20 = dict(zip(Test.Character,Test['B_Per20']))

# ฟังก์ชันวนเช็คค่า
def check5():
    for k,v in data.items():
        if v > t5[k[0]] or v < b5[k[0]]:
            checker.append(0)
        else :
            checker.append(1)
            
def check10():
    for k,v in data.items():
        if v > t10[k[0]] or v < b10[k[0]]:
            checker.append(0)
        else :
            checker.append(1)

def check15():
    for k,v in data.items():
        if v > t15[k[0]] or v < b15[k[0]]:
            checker.append(0)
        else :
            checker.append(1)
            
def check20():
    for k,v in data.items():
        if v > t20[k[0]] or v < b20[k[0]]:
            checker.append(0)
        else :
            checker.append(1)

# เรียกฟังก์ชัน
check20()
check_userTest['checker'] = checker

check_userTest

      Character  checker
27584         A        1
2451          B        1
502           C        0
10308         D        0
18545         E        1
7792          F        0
8012          G        1
12996         H        0
7512          I        1
6315          J        0
13646         K        1
27453         L        0
13315         M        1
27762         N        0
15442         O        1
25380         P        0
18320         Q        1
20155         R        1
8604          S        0
5613          T        1
4273          U        0
25656         V        1
4082          W        1
8254          X        1
14178         Y        1
36959         Z        0

In [7]:
# นับจำนวนที่อยู่ในและนอกteshold
# 1 = in >> real user
# 0 = out >> fake user
num = check_userTest['checker'].to_list()
num1 = 0
num0 = 0
for i in num:
    if i== 1:
        num1 += 1
    elif i == 0:
        num0 += 1

user = num1 / (num1+num0)*100

if user > 50:
    result = "real user"
elif user == 50:
    result = "unidentify"
elif user < 50:
    result = "fake user"


print("true = ",num1)
print("false = ",num0)    
print(f'{user:.2f}% = {result}')

true =  15
false =  11
57.69% = real user

In [8]:
# ฟังก์ชันไว้คำนวน %

def pec_check(functionCheck):
    checker2 = []
    
    # ฟังก์ชันวนเช็คค่า
    def check5():
        for k,v in data.items():
            if v > t5[k[0]] or v < b5[k[0]]:
                checker2.append(0)
            else :
                checker2.append(1)

    def check10():
        for k,v in data.items():
            if v > t10[k[0]] or v < b10[k[0]]:
                checker2.append(0)
            else :
                checker2.append(1)

    def check15():
        for k,v in data.items():
            if v > t15[k[0]] or v < b15[k[0]]:
                checker2.append(0)
            else :
                checker2.append(1)

    def check20():
        for k,v in data.items():
            if v > t20[k[0]] or v < b20[k[0]]:
                checker2.append(0)
            else :
                checker2.append(1)

    # เรียกฟังก์ชัน
    eval(functionCheck)

    
    num = checker2
    num1 = 0
    num0 = 0
    for i in num:
        if i== 1:
            num1 += 1
        elif i == 0:
            num0 += 1

    user = num1 / (num1+num0)*100

    if user > 50:
        result = "real user"
    elif user == 50:
        result = "unidentify"
    elif user < 50:
        result = "fake user"


    print("true = ",num1)
    print("false = ",num0)    
    print(f'{user:.2f}% = {result}')

In [28]:
output1 = wg.Output()
output2 = wg.Output()
output3 = wg.Output()
output4 = wg.Output()
display(HBox([output1,output2,output3,output4]))

def thresholdTest(Per5 = False ,Per10 = False ,Per15 = False ,Per20 = True):
    fig, ax = plt.subplots(figsize=(10,5))
    plt.scatter(Test['Character'],Test['TestPredictPlot'])
    plt.scatter(testcompare['Character'],testcompare['Time'],marker='+')
    
    plt.title(f"1key RNN Test")
    plt.xlabel("Character")
    plt.ylabel("Time : ms")
    
    output2.clear_output()
    output1.clear_output()
    output3.clear_output()
    output4.clear_output()
    
    if Per5 == True:
        plt.plot(Test['Character'],Test['T_Per5'],color="#E00296")
        plt.plot(Test['Character'],Test['B_Per5'],color="#E00296")
        with output1:
            print('threshold 5%')
            pec_check("check5()")
            print("--------------------")
        
    if Per10 == True:
        plt.plot(Test['Character'],Test['T_Per10'],color="red")
        plt.plot(Test['Character'],Test['B_Per10'],color="red")
        with output2:
            print('threshold 10%')
            pec_check("check10()")
            print("--------------------")
        
    if Per15 == True:
        plt.plot(Test['Character'],Test['T_Per15'],color="orange")
        plt.plot(Test['Character'],Test['B_Per15'],color="orange")
        with output3:
            print('threshold 15%')
            pec_check("check15()")
            print("--------------------")
        
        
    if Per20 == True:
        plt.plot(Test['Character'],Test['T_Per20'],color="green")
        plt.plot(Test['Character'],Test['B_Per20'],color="green")
        with output4:
            print('threshold 20%')
            pec_check("check20()")
            print("--------------------")
        
    plt.show()

wg.interact(thresholdTest ,Per5 = False ,Per10 = False ,Per15 = False ,Per20 = True)

HBox(children=(Output(), Output(), Output(), Output()))

interactive(children=(Checkbox(value=False, description='Per5'), Checkbox(value=False, description='Per10'), C…

## Train

In [10]:
# threshold Train
Train = pd.DataFrame()
Train['Character'] = Tthreshold['Character']
Train['TrainPredictPlot'] = Tthreshold['train']
Train['Per5'] = Tthreshold['train'] * 0.05
Train['Per10'] = Tthreshold['train'] * 0.1
Train['Per15'] = Tthreshold['train'] * 0.15
Train['Per20'] = Tthreshold['train'] * 0.2

Train['T_Per5'] = Tthreshold['train'] + Train['Per5']
Train['B_Per5'] = Tthreshold['train'] - Train['Per5']

Train['T_Per10'] = Tthreshold['train'] + Train['Per10']
Train['B_Per10'] = Tthreshold['train'] - Train['Per10']

Train['T_Per15'] = Tthreshold['train'] + Train['Per15']
Train['B_Per15'] = Tthreshold['train'] - Train['Per15']

Train['T_Per20'] = Tthreshold['train'] + Train['Per20']
Train['B_Per20'] = Tthreshold['train'] - Train['Per20']

Train

,Character,TrainPredictPlot,Per5,Per10,Per15,Per20,T_Per5,B_Per5,T_Per10,B_Per10,T_Per15,B_Per15,T_Per20,B_Per20
0,A,1005.90630,50.295315,100.590630,150.885945,201.181260,1056.201615,955.610985,1106.496930,905.315670,1156.792245,855.020355,1207.087560,804.725040
1,B,756.20170,37.810085,75.620170,113.430255,151.240340,794.011785,718.391615,831.821870,680.581530,869.631955,642.771445,907.442040,604.961360
2,C,775.33466,38.766733,77.533466,116.300199,155.066932,814.101393,736.567927,852.868126,697.801194,891.634859,659.034461,930.401592,620.267728
3,D,934.15094,46.707547,93.415094,140.122641,186.830188,980.858487,887.443393,1027.566034,840.735846,1074.273581,794.028299,1120.981128,747.320752
4,E,1059.33330,52.966665,105.933330,158.899995,211.866660,1112.299965,1006.366635,1165.266630,953.399970,1218.233295,900.433305,1271.199960,847.466640
5,F,982.15270,49.107635,98.215270,147.322905,196.430540,1031.260335,933.045065,1080.367970,883.937430,1129.475605,834.829795,1178.583240,785.722160
6,G,1026.53660,51.326830,102.653660,153.980490,205.307320,1077.863430,975.209770,1129.190260,923.882940,1180.517090,872.556110,1231.843920,821.229280
7,H,954.12470,47.706235,95.412470,143.118705,190.824940,1001.830935,906.418465,1049.537170,858.712230,1097.243405,811.005995,1144.949640,763.299760
8,I,893.47610,44.673805,89.347610,134.021415,178.695220,938.149905,848.802295,982.823710,804.128490,1027.497515,759.454685,1072.171320,714.780880
9,J,718.93585,35.946793,71.893585,107.840377,143.787170,754.882642,682.989057,790.829435,647.042265,826.776228,611.095472,862.723020,575.148680
10,K,736.41284,36.820642,73.641284,110.461926,147.282568,773.233482,699.592198,810.054124,662.771556,846.874766,625.950914,883.695408,589.130272
11,L,980.56450,49.028225,98.056450,147.084675,196.112900,1029.592725,931.536275,1078.620950,882.508050,1127.649175,833.479825,1176.677400,784.451600
12,M,966.53110,48.326555,96.653110,144.979665,193.306220,1014.857655,918.204545,1063.184210,869.877990,1111.510765,821.551435,1159.837320,773.224880
13,N,776.20917,38.810459,77.620917,116.431375,155.241834,815.019628,737.398711,853.830087,698.588253,892.640545,659.777795,931.451004,620.967336
14,O,1015.84515,50.792258,101.584515,152.376772,203.169030,1066.637407,965.052892,1117.429665,914.260635,1168.221922,863.468377,1219.014180,812.676120
15,P,622.51560,31.125780,62.251560,93.377340,124.503120,653.641380,591.389820,684.767160,560.264040,715.892940,529.138260,747.018720,498.012480
16,Q,1347.56430,67.378215,134.756430,202.134645,269.512860,1414.942515,1280.186085,1482.320730,1212.807870,1549.698945,1145.429655,1617.077160,1078.051440
17,R,834.26263,41.713132,83.426263,125.139394,166.852526,875.975761,792.549498,917.688893,750.836367,959.402024,709.123235,1001.115156,667.410104
18,S,861.87380,43.093690,86.187380,129.281070,172.374760,904.967490,818.780110,948.061180,775.686420,991.154870,732.592730,1034.248560,689.499040
19,T,645.34436,32.267218,64.534436,96.801654,129.068872,677.611578,613.077142,709.878796,580.809924,742.146014,548.542706,774.413232,516.275488
20,U,743.25000,37.162500,74.325000,111.487500,148.650000,780.412500,706.087500,817.575000,668.925000,854.737500,631.762500,891.900000,594.600000
21,V,1113.27640,55.663820,111.327640,166.991460,222.655280,1168.940220,1057.612580,1224.604040,1001.948760,1280.267860,946.284940,1335.931680,890.621120
22,W,899.25775,44.962888,89.925775,134.888662,179.851550,944.220637,854.294863,989.183525,809.331975,1034.146412,764.369087,1079.109300,719.406200
23,X,562.81160,28.140580,56.281160,84.421740,112.562320,590.952180,534.671020,619.092760,506.530440,647.233340,478.389860,675.373920,450.249280
24,Y,512.96124,25.648062,51.296124,76.944186,102.592248,538.609302,487.313178,564.257364,461.665116,589.905426,436.017054,615.553488,410.368992
25,Z,854.76526,42.738263,85.476526,128.214789,170.953052,897.503523,812.026997,940.241786,769.288734,982.980049,726.550471,1025.718312,683.812208

In [11]:
check_userTrain = pd.DataFrame()

# เก็บค่าที่อยู่นอกหรือใน teshold
checker = []
check_userTrain['Character'] = testcompare['Character'] 
    
# แปลงเป็น dic
data = dict(zip(testcompare['Character'],testcompare['Time']))

t5 = dict(zip(Train.Character,Train['T_Per5']))
b5 = dict(zip(Train.Character,Train['B_Per5']))

t10 = dict(zip(Train.Character,Train['T_Per10']))
b10 = dict(zip(Train.Character,Train['B_Per10']))

t15 = dict(zip(Train.Character,Train['T_Per15']))
b15 = dict(zip(Train.Character,Train['B_Per15']))

t20 = dict(zip(Train.Character,Train['T_Per20']))
b20 = dict(zip(Train.Character,Train['B_Per20']))

# ฟังก์ชันวนเช็คค่า
def check5():
    for k,v in data.items():
        if v > t5[k[0]] or v < b5[k[0]]:
            checker.append(0)
        else :
            checker.append(1)
            
def check10():
    for k,v in data.items():
        if v > t10[k[0]] or v < b10[k[0]]:
            checker.append(0)
        else :
            checker.append(1)

def check15():
    for k,v in data.items():
        if v > t15[k[0]] or v < b15[k[0]]:
            checker.append(0)
        else :
            checker.append(1)
            
def check20():
    for k,v in data.items():
        if v > t20[k[0]] or v < b20[k[0]]:
            checker.append(0)
        else :
            checker.append(1)

# เรียกฟังก์ชัน
check20()
check_userTrain['checker'] = checker

check_userTrain

      Character  checker
27584         A        1
2451          B        0
502           C        0
10308         D        0
18545         E        1
7792          F        0
8012          G        1
12996         H        0
7512          I        1
6315          J        0
13646         K        0
27453         L        1
13315         M        1
27762         N        0
15442         O        1
25380         P        0
18320         Q        1
20155         R        1
8604          S        0
5613          T        0
4273          U        0
25656         V        1
4082          W        1
8254          X        0
14178         Y        0
36959         Z        0

In [12]:
# นับจำนวนที่อยู่ในและนอกteshold
# 1 = in >> real user
# 0 = out >> fake user
num = check_userTrain['checker'].to_list()
num1 = 0
num0 = 0
for i in num:
    if i== 1:
        num1 += 1
    elif i == 0:
        num0 += 1

user = num1 / (num1+num0)*100

if user > 50:
    result = "real user"
elif user == 50:
    result = "unidentify"
elif user < 50:
    result = "fake user"


print("true = ",num1)
print("false = ",num0)    
print(f'{user:.2f}% = {result}')

true =  11
false =  15
42.31% = fake user

In [13]:
# ฟังก์ชันไว้คำนวน %

def pec_check(functionCheck):
    checker2 = []
    
    # ฟังก์ชันวนเช็คค่า
    def check5():
        for k,v in data.items():
            if v > t5[k[0]] or v < b5[k[0]]:
                checker2.append(0)
            else :
                checker2.append(1)

    def check10():
        for k,v in data.items():
            if v > t10[k[0]] or v < b10[k[0]]:
                checker2.append(0)
            else :
                checker2.append(1)

    def check15():
        for k,v in data.items():
            if v > t15[k[0]] or v < b15[k[0]]:
                checker2.append(0)
            else :
                checker2.append(1)

    def check20():
        for k,v in data.items():
            if v > t20[k[0]] or v < b20[k[0]]:
                checker2.append(0)
            else :
                checker2.append(1)

    # เรียกฟังก์ชัน
    eval(functionCheck)

    
    num = checker2
    num1 = 0
    num0 = 0
    for i in num:
        if i== 1:
            num1 += 1
        elif i == 0:
            num0 += 1

    user = num1 / (num1+num0)*100

    if user > 50:
        result = "real user"
    elif user == 50:
        result = "unidentify"
    elif user < 50:
        result = "fake user"


    print("true = ",num1)
    print("false = ",num0)    
    print(f'{user:.2f}% = {result}')

In [17]:
output1 = wg.Output()
output2 = wg.Output()
output3 = wg.Output()
output4 = wg.Output()
display(HBox([output1,output2,output3,output4]))

def thresholdTrain(Per5 = False ,Per10 = False ,Per15 = False ,Per20 = True):
    fig, ax = plt.subplots(figsize=(10,5))
    plt.scatter(Train['Character'],Train['TrainPredictPlot'])
    plt.scatter(testcompare['Character'],testcompare['Time'],marker='+')
    
    plt.title(f"1key RNN Train")
    plt.xlabel("Character")
    plt.ylabel("Time : ms")
    
    output2.clear_output()
    output1.clear_output()
    output3.clear_output()
    output4.clear_output()
    
    if Per5 == True:
        plt.plot(Train['Character'],Train['T_Per5'],color="#E00296")
        plt.plot(Train['Character'],Train['B_Per5'],color="#E00296")
        with output1:
            print('threshold 5%')
            pec_check("check5()")
            print("--------------------")
        
    if Per10 == True:
        plt.plot(Train['Character'],Train['T_Per10'],color="red")
        plt.plot(Train['Character'],Train['B_Per10'],color="red")
        with output2:
            print('threshold 10%')
            pec_check("check10()")
            print("--------------------")
        
    if Per15 == True:
        plt.plot(Train['Character'],Train['T_Per15'],color="orange")
        plt.plot(Train['Character'],Train['B_Per15'],color="orange")
        with output3:
            print('threshold 15%')
            pec_check("check15()")
            print("--------------------")
        
        
    if Per20 == True:
        plt.plot(Train['Character'],Train['T_Per20'],color="green")
        plt.plot(Train['Character'],Train['B_Per20'],color="green")
        with output4:
            print('threshold 20%')
            pec_check("check20()")
            print("--------------------")
        
    plt.show()

wg.interact(thresholdTrain ,Per5 = False ,Per10 = False ,Per15 = False ,Per20 = True)

HBox(children=(Output(), Output(), Output(), Output()))

interactive(children=(Checkbox(value=False, description='Per5'), Checkbox(value=False, description='Per10'), C…